export const ADD_STUDENT = "ADD_STUDENT";
export const RETRIEVE_STUDENT = "RETRIEVE_STUDENT";
export const RETRIEVE_STUDENT_FAILED = "RETRIEVE_STUDENT_FAILED";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const ADD_STUDENT_FAILED = "ADD_STUDENT_FAILED";
export const RETRIEVE_SINGLE_STUDENT = "RETRIEVE_SINGLE_STUDENT";